// Plausible fake data for the Agentic Harness operator dashboard
window.HARNESS_DATA = {
  tickets: [
    {
      id: "HARN-2043",
      title: "Add retry-with-backoff to the Figma design spec extractor",
      status: "active",
      statusLabel: "Developer · unit-02",
      phase: 2, // 0..4
      profile: "sitecore",
      size: "2 units",
      elapsed: "08:42",
      budget: "45m",
      reviewer: "—",
      branch: "ai/HARN-2043",
      analyst: "opus",
      unitsTotal: 2,
      unitsDone: 1,
      author: "m.park",
      created: "02:14",
      kind: "story",
    },
    {
      id: "HARN-2041",
      title: "Normalize ADF rich-text in Jira webhook adapter",
      status: "ok",
      statusLabel: "PR draft ready",
      phase: 4,
      profile: "salesforce",
      size: "1 unit",
      elapsed: "11:08",
      budget: "30m",
      reviewer: "judge · approved",
      branch: "ai/HARN-2041",
      unitsTotal: 1,
      unitsDone: 1,
      author: "s.okafor",
      created: "01:47",
      kind: "task",
    },
    {
      id: "HARN-2039",
      title: "Sitecore experience accelerator — fix rendering variant inheritance",
      status: "warn",
      statusLabel: "Needs clarification",
      phase: 0,
      profile: "sitecore",
      size: "—",
      elapsed: "—",
      budget: "—",
      reviewer: "—",
      branch: "—",
      unitsTotal: 0,
      unitsDone: 0,
      author: "r.lindqvist",
      created: "01:32",
      kind: "bug",
    },
    {
      id: "HARN-2038",
      title: "Add playwright visual-regression snapshot for checkout v2",
      status: "active",
      statusLabel: "Code review",
      phase: 3,
      profile: "sitecore",
      size: "3 units",
      elapsed: "22:19",
      budget: "60m",
      reviewer: "in progress",
      branch: "ai/HARN-2038",
      unitsTotal: 3,
      unitsDone: 3,
      author: "d.iwasaki",
      created: "01:12",
      kind: "story",
    },
    {
      id: "HARN-2036",
      title: "Salesforce Apex trigger — prevent recursive update on Opportunity",
      status: "err",
      statusLabel: "Failed · 3/3 retries",
      phase: 2,
      profile: "salesforce",
      size: "2 units",
      elapsed: "41:02",
      budget: "45m",
      reviewer: "escalate",
      branch: "ai/HARN-2036",
      unitsTotal: 2,
      unitsDone: 0,
      author: "a.mensah",
      created: "00:51",
      kind: "bug",
    },
    {
      id: "HARN-2035",
      title: "Inject MCP config + runtime CLAUDE.md into worktree",
      status: "ok",
      statusLabel: "Merged",
      phase: 4,
      profile: "harness",
      size: "1 unit",
      elapsed: "06:24",
      budget: "20m",
      reviewer: "approved",
      branch: "ai/HARN-2035",
      unitsTotal: 1,
      unitsDone: 1,
      author: "s.okafor",
      created: "00:42",
      kind: "task",
    },
    {
      id: "HARN-2034",
      title: "Client profile auto-detection — fall back to platform hint",
      status: "cool",
      statusLabel: "Queued",
      phase: 0,
      profile: "—",
      size: "—",
      elapsed: "00:00",
      budget: "—",
      reviewer: "—",
      branch: "—",
      unitsTotal: 0,
      unitsDone: 0,
      author: "m.park",
      created: "00:18",
      kind: "story",
    },
    {
      id: "HARN-2031",
      title: "Dashboard — filter by stuck tickets under custom SLA",
      status: "active",
      statusLabel: "Planner",
      phase: 1,
      profile: "harness",
      size: "est 4",
      elapsed: "01:12",
      budget: "60m",
      reviewer: "—",
      branch: "ai/HARN-2031",
      unitsTotal: 4,
      unitsDone: 0,
      author: "j.reyes",
      created: "00:09",
      kind: "story",
    },
  ],

  // Logs keyed by ticket id
  logs: {
    "HARN-2043": [
      ["02:14.103", "info", "L1 analyst enriched · size=<b>2 units</b> · 3 AC · 2 edge cases"],
      ["02:14.421", "info", "Spawned worktree <em>ai/HARN-2043</em> · 7 skills injected"],
      ["02:14.502", "info", "MCP config linked · playwright · figma"],
      ["02:15.002", "pass", "Planner → 2 atomic units · DAG valid · no file conflicts"],
      ["02:15.311", "pass", "Plan-reviewer → AC coverage complete"],
      ["02:15.540", "info", "Spawned <b>developer/unit-01</b> (worktree)"],
      ["02:15.541", "info", "Spawned <b>developer/unit-02</b> (worktree · depends unit-01)"],
      ["02:17.881", "warn", "unit-01 retry 1/3 · <b>test_backoff_sequence</b> failed · assert 2.0 == 1.8"],
      ["02:18.442", "info", "unit-01 adjusting jitter envelope"],
      ["02:19.204", "pass", "unit-01 → 4 tests green · committed <em>c2a91f</em>"],
      ["02:19.518", "info", "unit-02 unblocked · reading src/figma/client.py"],
      ["02:21.556", "info", "merge-coordinator → dependencies resolved"],
      ["02:22.014", "info", "unit-02 added httpx retry policy + exponential backoff"],
      ["02:22.880", "info", "unit-02 writing tests/test_figma_retry.py"],
    ],
    "HARN-2041": [
      ["01:47.220", "info", "L1 analyst enriched · size=<b>1 unit</b>"],
      ["01:47.905", "info", "Spawned worktree <em>ai/HARN-2041</em>"],
      ["01:48.770", "info", "Developer exploring services/l1_preprocessing/adapters/jira.py"],
      ["01:51.112", "pass", "10 tests green · committed <em>7f8a12</em>"],
      ["01:51.602", "info", "Code reviewer → APPROVED · 0 findings"],
      ["01:52.011", "pass", "Draft PR opened · +82 −14 · 3 files"],
    ],
    "HARN-2036": [
      ["00:51.004", "info", "L1 enriched · 2 units · platform=salesforce"],
      ["00:51.882", "info", "Spawned worktree"],
      ["00:53.400", "warn", "unit-01 retry 1/3 · apex trigger recursion depth exceeded"],
      ["00:58.120", "warn", "unit-01 retry 2/3 · context.trigger.oldMap null"],
      ["01:02.440", "err",  "unit-01 retry 3/3 · same failure mode"],
      ["01:02.880", "err",  "<em>ESCALATE</em> · team-lead abandoning unit · human intervention required"],
    ],
    "HARN-2038": [
      ["01:12.103", "info", "L1 enriched · 3 units"],
      ["01:18.441", "pass", "unit-01 committed <em>2b40ae</em>"],
      ["01:24.018", "pass", "unit-02 committed <em>d19c33</em>"],
      ["01:30.771", "pass", "unit-03 committed <em>f01abc</em>"],
      ["01:32.009", "info", "Code reviewer scanning diff · 14 files"],
    ],
    "HARN-2031": [
      ["00:09.002", "info", "L1 enriched · estimated 4 units"],
      ["00:10.441", "info", "Planner decomposing into units"],
    ],
    "HARN-2039": [
      ["01:32.112", "warn", "Analyst → INFO_REQUEST · 2 clarifying questions posted to Jira"],
      ["01:32.400", "info", "Pipeline paused · awaiting reply"],
    ],
    "HARN-2035": [
      ["00:42.004", "info", "L1 enriched"],
      ["00:46.100", "pass", "All tests green · merged <em>ai/HARN-2035</em>"],
    ],
    "HARN-2034": [
      ["00:18.001", "info", "Queued · waiting on worktree capacity"],
    ],
  },

  kpis: [
    { label: "PRs shipped / 24h", val: "17", suffix: "↑ 4", sub: "vs. prev window" },
    { label: "Median cycle time", val: "11m", suffix: "42s", sub: "analyst → draft PR" },
    { label: "Judge pass-through", val: "68", suffix: "%", sub: "reviewer findings upheld" },
    { label: "Stuck tickets", val: "2", suffix: "", sub: "awaiting human clarify" },
  ],

  phases: [
    { layer: "L1", name: "Analyst" },
    { layer: "L2", name: "Plan + review" },
    { layer: "L2", name: "Develop" },
    { layer: "L2", name: "Review + judge" },
    { layer: "L3", name: "Architecture" },
  ],

  agents: [
    { handle: "@team-lead", role: "Conductor", state: "active" },
    { handle: "@planner", role: "Decomposer", state: "idle" },
    { handle: "@developer/01", role: "Builder", state: "ok" },
    { handle: "@developer/02", role: "Builder", state: "active" },
    { handle: "@reviewer", role: "Reviewer", state: "idle" },
    { handle: "@judge", role: "Skeptic", state: "idle" },
    { handle: "@qa", role: "QA", state: "idle" },
  ],
};
