"""Data models for the L1 Pre-Processing pipeline.

These models define the contract between L1 (pre-processing), L2 (agent team execution),
and L3 (PR review & feedback). All inter-layer communication uses these structures.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field

# --- Enums ---


class TicketSource(StrEnum):
    """Supported ticket management systems."""

    JIRA = "jira"
    ADO = "ado"


class TicketType(StrEnum):
    """Supported ticket types."""

    STORY = "story"
    TASK = "task"
    BUG = "bug"


class SizeClassification(StrEnum):
    """Ticket size classification for determining agent team composition."""

    SMALL = "small"  # 1 dev teammate
    MEDIUM = "medium"  # 2-3 dev teammates
    LARGE = "large"  # 4+ dev teammates, may need decomposition


class TestType(StrEnum):
    """Types of tests that can be generated."""

    UNIT = "unit"
    INTEGRATION = "integration"
    E2E = "e2e"


# --- Supporting Models ---


IMAGE_CONTENT_TYPES = frozenset({
    "image/png",
    "image/jpeg",
    "image/gif",
    "image/webp",
})

MAX_IMAGE_ATTACHMENT_BYTES = 5 * 1024 * 1024  # 5 MB


class Attachment(BaseModel):
    """A file attachment on a ticket."""

    filename: str
    url: str
    content_type: str = ""
    local_path: str = ""  # Set after download; absolute path to local file

    @property
    def is_design_image(self) -> bool:
        """True if this attachment is a supported image type."""
        return self.content_type.lower() in IMAGE_CONTENT_TYPES


class LinkedItem(BaseModel):
    """A linked issue/ticket reference."""

    id: str
    source: TicketSource
    relationship: str = ""  # e.g. "blocks", "is blocked by", "relates to"
    title: str = ""


class CallbackConfig(BaseModel):
    """Configuration for writing back to the source ticket system."""

    base_url: str
    ticket_id: str
    source: TicketSource
    auth_token: str = Field(default="", repr=False)  # Never logged


class TestScenario(BaseModel):
    """A test scenario generated by the ticket analyst."""

    name: str
    test_type: TestType
    description: str
    criteria_ref: str = ""  # Back-reference to which acceptance criterion this validates


class SizeAssessment(BaseModel):
    """Analyst's assessment of ticket size and complexity."""

    classification: SizeClassification
    estimated_units: int = Field(ge=1, description="Number of independent implementation units")
    recommended_dev_count: int = Field(ge=1, le=10)
    decomposition_needed: bool = False
    rationale: str = ""


class DesignSpec(BaseModel):
    """Structured design specification extracted from Figma."""

    figma_url: str
    components: list[str] = Field(default_factory=list)
    layout_patterns: list[str] = Field(default_factory=list)
    color_tokens: dict[str, str] = Field(default_factory=dict)
    typography: dict[str, str] = Field(default_factory=dict)
    interactive_states: list[str] = Field(default_factory=list)
    responsive_breakpoints: list[str] = Field(default_factory=list)
    rendered_frames: list[str] = Field(
        default_factory=list,
        description="Local paths to rendered PNG images of Figma frames",
    )
    raw_extraction: str = ""  # Full extraction text for agent context


# --- Core Pipeline Models ---


class TicketPayload(BaseModel):
    """Normalized ticket from Jira or ADO, before enrichment.

    This is the common format produced by the source-specific adapters.
    """

    source: TicketSource
    id: str
    ticket_type: TicketType
    title: str
    description: str = ""
    acceptance_criteria: list[str] = Field(default_factory=list)
    attachments: list[Attachment] = Field(default_factory=list)
    linked_items: list[LinkedItem] = Field(default_factory=list)
    labels: list[str] = Field(default_factory=list)
    priority: str = ""
    assignee: str = ""
    callback: CallbackConfig | None = None
    raw_payload: dict[str, object] = Field(
        default_factory=dict, description="Original webhook payload"
    )


class EnrichedTicket(TicketPayload):
    """Ticket after analyst enrichment, ready for L2 Agent Team execution."""

    generated_acceptance_criteria: list[str] = Field(default_factory=list)
    test_scenarios: list[TestScenario] = Field(default_factory=list)
    edge_cases: list[str] = Field(default_factory=list)
    size_assessment: SizeAssessment | None = None
    figma_design_spec: DesignSpec | None = None
    platform_profile: str | None = None  # e.g. "sitecore", "salesforce"
    analyst_notes: str = ""
    enriched_at: datetime | None = None


class InfoRequest(BaseModel):
    """Analyst requests more information from the ticket author."""

    ticket_id: str
    source: TicketSource
    questions: list[str] = Field(min_length=1)
    context: str = ""  # Why the analyst needs this info
    callback: CallbackConfig | None = None


class SubTicketSpec(BaseModel):
    """Specification for a sub-ticket to be created."""

    title: str
    description: str
    ticket_type: TicketType
    acceptance_criteria: list[str] = Field(default_factory=list)
    estimated_size: SizeClassification = SizeClassification.SMALL
    depends_on: list[str] = Field(default_factory=list)


class DecompositionPlan(BaseModel):
    """Analyst recommends splitting the ticket into sub-tickets."""

    ticket_id: str
    source: TicketSource
    reason: str
    sub_tickets: list[SubTicketSpec] = Field(default_factory=list)
    dependency_order: list[str] = Field(
        default_factory=list, description="Sub-ticket IDs in execution order"
    )
    callback: CallbackConfig | None = None


# --- Analyst Output (Discriminated Union) ---

AnalystOutput = EnrichedTicket | InfoRequest | DecompositionPlan
"""The analyst produces one of three outputs:
- EnrichedTicket: ticket is complete, enriched, ready for L2
- InfoRequest: analyst needs more info, ticket goes to "Needs Clarification"
- DecompositionPlan: ticket too large, needs splitting into sub-tickets
"""


def classify_analyst_output(
    output: EnrichedTicket | InfoRequest | DecompositionPlan,
) -> Literal["enriched", "info_request", "decomposition"]:
    """Classify the analyst output type for routing decisions."""
    if isinstance(output, EnrichedTicket):
        return "enriched"
    if isinstance(output, InfoRequest):
        return "info_request"
    return "decomposition"
